---
- name: get current running-config
  ios_command:
    commands: show running-config
    provider: "{{ provider }}"
  register: config

- name: get current configured ntp servers
  set_fact: _servers="{{ config.stdout[0] | regex_findall('^ntp server (\S+)') }}"

- name: remove old ntp servers
  ios_config:
    lines:
      - "no ntp server {{ item }}"
    provider: "{{ provider }}"
    force: yes
  with_items: "{{ _servers }}"
  #when: item not in ntp_servers

- name: configure ios ntp parameters
  ios_config:
    src: ios.j2
    provider: "{{ provider }}"

